// Package content takes static content files in a directory and creates a Go source file declaring strings with the static content.
// Useful when you want to embed static Web content inside a Go binary.
// The generated string for the file 'index.html' is 'index_html' for example.
// Note: All files are read into memory, they should not be very big.

package content

import (
	"os"
	"bytes"
	"fmt"
	"io/ioutil"
	"path/filepath"
	"strings"
)

func GenerateContent(staticDir string, outputDir string, outputFile string, packageName string) error {

	staticOut := bytes.NewBufferString("// Do Not Edit; Auto Generated by the 'content' package\n\n")
	staticOut.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	err := filepath.Walk(staticDir, func(path string, info os.FileInfo, err error) error {
		if !info.IsDir() {
			stringName := strings.Replace(filepath.Base(path), ".", "_", -1)
			staticOut.WriteString(fmt.Sprintf("const %s = `", stringName))
			thisFile, err := ioutil.ReadFile(path)
			if err != nil {
				return fmt.Errorf("error reading static content file '%s': %v", path, err)
			}
			staticOut.Write(thisFile)
			staticOut.WriteString("`\n\n")
		}
		return nil
	})

	staticOutFile, err := os.Create(filepath.Join(outputDir, outputFile))
	if err != nil {
		return fmt.Errorf("error creating Go source file '%s': %v", outputFile, err)
	}

	_, err = staticOut.WriteTo(staticOutFile)
	if err != nil {
		staticOutFile.Close()
		return fmt.Errorf("error writing Go source file '%s': %v", outputFile, err)
	}

	err = staticOutFile.Close()
	if err != nil {
		return fmt.Errorf("error closing Go source file '%s': %v", outputFile, err)
	}

	return nil
}
